### PR TITLE
Remove checked in binaries.

### PR DESCRIPTION
**Pull request by godofredoc**
Checking in binaries in the git repositories is a security risk because
they can't be reviewed.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chinmaygarde** [comment]
//build/win seems unused and was from the inherited Chromium buildroot. Can you please remove everything and attempt a buildroot updates?

**Review by chinmaygarde — APPROVED** [review]
LGTM either way.

**Comment by godofredoc** [comment]
> //build/win seems unused and was from the inherited Chromium buildroot. Can you please remove everything and attempt a buildroot update?

By buildroot update do you mean to roll the change to the engine?

**Comment by chinmaygarde** [comment]
Right. The buildroot roll process is manual. In case this introduces a break later, it may have to be reverted.

**Pull request merged**
