### PR TITLE
Roll to mojo/public @ b4b78b6b7b0696d87f9d7a20d8239854aeb28446

### PR DESCRIPTION
**Pull request by jamesr**
This prepares the buildroot for a roll to mojo/public to rev
e8a607c6f017017faf9aac73bc881c419a71f902. flutter/DEPS will have
to update to this buildroot in the same commit as updating mojo/public
This is mostly just path fixes for renames in the C API.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by jamesr** [comment]
Hmm whoops, need to update some #includes too.  New patch incoming...

**Comment by jamesr** [comment]
This includes the EDK roll, as a separate commit to try to keep things easier to review, and rolls to mojo/public @ e8a607c6f017017faf9aac73bc881c419a71f902 which has some dart generation fixes that'll be needed.  PTAL

**Comment by chinmaygarde** [comment]
lgtm

**Comment by chinmaygarde** [comment]
This patch seems to have broken the Linux engine host target. The GN step is trying to refer to a file no longer present [mojo/public/c/BUILD.gn ](https://gist.github.com/chinmaygarde/f537a02fbbca0bce00552a44e3a74671)

**Comment by chinmaygarde** [comment]
@jamesr: This patch was accompanied by a change in the engine which I think you reverted. https://github.com/flutter/engine/commit/4014a5be4836ef28375f767614dd51221c35b174. I have a suspicion that you either need to revert this one too or just patch the engine.

**Pull request merged**
