### PR TITLE
Increase section alignment to 64k on Android.

### PR DESCRIPTION
**Pull request by rmacnak-google**
go/16k-app-guide

### CODE REVIEW

**Comment by rmacnak-google** [comment]
```
before$ readelf --segments out/android_release_arm64/libflutter.so

Elf file type is DYN (Shared object file)
Entry point 0x0
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000230 0x0000000000000230  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000003e4490 0x00000000003e4490  R      0x1000
  LOAD           0x00000000003e44c0 0x00000000003e54c0 0x00000000003e54c0
                 0x0000000000620320 0x0000000000620320  R E    0x1000
  LOAD           0x0000000000a047e0 0x0000000000a067e0 0x0000000000a067e0
                 0x0000000000067f08 0x0000000000067f08  RW     0x1000
  LOAD           0x0000000000a6c6e8 0x0000000000a6f6e8 0x0000000000a6f6e8
                 0x00000000000ca7e4 0x00000000000d92c8  RW     0x1000
  DYNAMIC        0x0000000000a69a80 0x0000000000a6ba80 0x0000000000a6ba80
                 0x0000000000000210 0x0000000000000210  RW     0x8
  GNU_RELRO      0x0000000000a047e0 0x0000000000a067e0 0x0000000000a067e0
                 0x0000000000067f08 0x0000000000068820  R      0x1
  GNU_EH_FRAME   0x0000000000231680 0x0000000000231680 0x0000000000231680
                 0x000000000006372c 0x000000000006372c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x00000000000000bc 0x00000000000000bc  R      0x4

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .note.android.ident .note.gnu.build-id .dynsym .gnu.version .gnu.version_r .gnu.hash .hash .dynstr .rela.dyn .rela.plt .rodata .eh_frame_hdr .eh_frame 
   02     .text .plt 
   03     .data.rel.ro .init_array .fini_array .dynamic .got .got.plt 
   04     .data .bss 
   05     .dynamic 
   06     .data.rel.ro .init_array .fini_array .dynamic .got .got.plt 
   07     .eh_frame_hdr 
   08     
   09     .note.android.ident .note.gnu.build-id 

after$ readelf --segments out/android_release_arm64/libflutter.so

Elf file type is DYN (Shared object file)
Entry point 0x0
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000230 0x0000000000000230  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000003e4490 0x00000000003e4490  R      0x10000
  LOAD           0x00000000003e44c0 0x00000000003f44c0 0x00000000003f44c0
                 0x0000000000620320 0x0000000000620320  R E    0x10000
  LOAD           0x0000000000a047e0 0x0000000000a247e0 0x0000000000a247e0
                 0x0000000000067f08 0x0000000000067f08  RW     0x10000
  LOAD           0x0000000000a6c6e8 0x0000000000a9c6e8 0x0000000000a9c6e8
                 0x00000000000ca7e4 0x00000000000d92c8  RW     0x10000
  DYNAMIC        0x0000000000a69a80 0x0000000000a89a80 0x0000000000a89a80
                 0x0000000000000210 0x0000000000000210  RW     0x8
  GNU_RELRO      0x0000000000a047e0 0x0000000000a247e0 0x0000000000a247e0
                 0x0000000000067f08 0x0000000000068820  R      0x1
  GNU_EH_FRAME   0x0000000000231680 0x0000000000231680 0x0000000000231680
                 0x000000000006372c 0x000000000006372c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x00000000000000bc 0x00000000000000bc  R      0x4

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .note.android.ident .note.gnu.build-id .dynsym .gnu.version .gnu.version_r .gnu.hash .hash .dynstr .rela.dyn .rela.plt .rodata .eh_frame_hdr .eh_frame 
   02     .text .plt 
   03     .data.rel.ro .init_array .fini_array .dynamic .got .got.plt 
   04     .data .bss 
   05     .dynamic 
   06     .data.rel.ro .init_array .fini_array .dynamic .got .got.plt 
   07     .eh_frame_hdr 
   08     
   09     .note.android.ident .note.gnu.build-id 
```

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
What consequences can we expect from this patch? Are there golem benchmarks?

**Comment by dnfield** [comment]
@rmacnak-google - specifically has Golem run on https://dart-review.googlesource.com/c/sdk/+/321302 and did it result in anything of note?

**Comment by rmacnak-google** [comment]
I wouldn't expect performance changes until the devices are running a kernel with 16k pages enabled. This just makes the engine binary forward compatible with that happening.

**Comment by rmacnak-google** [comment]
It is expected to increase the uncompressed engine binary size by up to 60k per segments, but it's all zeros so the compressed engine binary size should be basically the same.

**Pull request merged**
