### PR TITLE
Add third_party/vulkan to .gitignore, it is pulled via DEPS

### PR DESCRIPTION
**Pull request by jamesr**

### CODE REVIEW

**Comment by jamesr** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
This was already done in https://github.com/flutter/buildroot/commit/3ee1945972f4b3b5aab0a8f3835d99e3b41d20a4

**Comment by chinmaygarde** [comment]
Ah, I see what happened. We updated buildroot but did not update the flutter/DEPS to point to the updated buildroot. Hold on, will submit a patch in flutter/engine.

**Comment by jamesr** [comment]
Oh, that explains it.  Will close this.

**Pull request closed without merging**
