### PR TITLE
Enable codeql in buildroot repo.

### PR DESCRIPTION
**Pull request by godofredoc**
Enables codeql static analysis for buildroot repository.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
Can you remind me what this does? This repo isn't really standalone, and only semantically makes sense when paired with the engine repo.

**Comment by godofredoc** [comment]
This tool runs static analysis in the python scripts to find potential vulnerabilities.

**Comment by godofredoc** [comment]
> This tool runs static analysis in the python scripts to find potential vulnerabilities.

By the way it should not block anything just report the findings in the security tab.

**Comment by zanderso** [comment]
> This tool runs static analysis in the python scripts to find potential vulnerabilities.

Got it. Thanks. I think this will have limited value since the scripts are not user-facing, and we control all the inputs, but turning it on seems harmless.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
