### PR TITLE
Read vs_toolchain from data.json.

### PR DESCRIPTION
**Pull request by godofredoc**
If the vs toolchain exists locally read the parameters from the data.json file. This prevents from force downloading the toolchain when DEPOT_TOOLS_WIN_TOOLCHAIN_ROOT is set.

Bug: https://github.com/flutter/flutter/issues/127734

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
I have to admit that I'm not super-familiar with how this script works, but it looks like the wayward `print` that is confusing GN is coming from here:

https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/win_toolchain/get_toolchain_if_necessary.py#180

That is, if the timestamp files for the toolchain fail to match the timestamps of the files, or the timestamp files don't exist, then they are re-computed, which is preceded by the extra print. Would it be possible to diagnose why that is happening before making a change to this script?

**Comment by zanderso** [comment]
From PR triage: @godofredoc are you planning to continue with this PR?

**Comment by godofredoc** [comment]
> From PR triage: @godofredoc are you planning to continue with this PR?

Yes, although I'll need to set some time aside to continue the investigation.

**Comment by godofredoc** [comment]
I'll follow up on this PR to implement it differently

**Comment by godofredoc** [comment]
Closing as obsolete.

**Pull request closed without merging**
