### PR TITLE
Add boringssl generated files

### PR DESCRIPTION
**Pull request by zanderso**
This change adds the generated files for boringssl to Flutter's buildroot. This will let us DEPS boringssl into //third_party/boringssl instead of //dart/third_party/boringssl.

@abarth

### CODE REVIEW

**Comment by abarth** [comment]
Is there a benefit to checking these files into this repository as opposed to hosting them in another repository and using DEPS to pull them in?  I imagine many people who want to use boringssl will need the same files.  Rather than making N copies, why not put the files in a repository that can be shared by all of the clients?

**Comment by zanderso** [comment]
No, I don't think so. I'll request a repo for the generated files over on dart-lang.

**Comment by chinmaygarde** [comment]
Can we close this ticket?

**Comment by zanderso** [comment]
Yes.

**Pull request closed without merging**
