### PR TITLE
Sync vs_toolchain.py with Chromium.

### PR DESCRIPTION
**Pull request by bungeman**
In particular this brings in a newer Windows SDK.

### CODE REVIEW

**Comment by bungeman** [comment]
@chinmaygarde Unfortunately, I can't seem to test this in a simple way right now because if I try rolling flutter DEPS for src/ to this change locally, the icu build in flutter fails due to the changes made to this repo around using fuchsia's icu (in particular the move of no_rtti up one level).

**Comment by bungeman** [comment]
Maybe it is being updated, but maybe https://github.com/flutter/buildroot/blob/1c9494e60378bd119d910d530344077fc091b3a5/build/config/win/BUILD.gn#L16 is keeping us from seeing it?

**Comment by chinmaygarde** [comment]
@bungeman It is not clear to me what the next steps are w.r.t this PR. Happy to help test this for you however.

**Comment by bungeman** [comment]
The status of this is, it would probably be a good idea to update, but it isn't necessary right now.

The issue which prompted this turns out to be that in dwrite_3.h a number of enums, interfaces, and macros are behind NTDDI_VERSION checks. I believe this is in error, since these are immutable enums, interfaces, and macros (if ever something needs to be added new enums, interfaces, and macros will be introduced). NTDDI_VERSION seems to be intended to hide functions and struct extensions, and DirectWrite only has one function. On the other hand, DirectWrite headers are in fact doing this, so setting NTDDI_VERSION=0x06030000 prevents any declarations in DirectWrite headers past Windows 8.1 from being seen (even thought the SDK is much newer). This prevents us from simply using "QueryInterface" to look for the newer interfaces at runtime (without having our own declarations).

As a result, what we've done on the Skia side to work around what seems to be a more general issue with DirectWrite headers is to just undefine NTDDI_VERSION (and related) if defined by the build, just for DirectWrite related translation units. This is slightly dangerous in the sense that Skia could use newer API and get it through, but Skia also will run tests on Test-Win7-Clang-Golo-CPU-AVX-x86_64-Debug-All-NativeFonts which runs all of this code on Windows 7, so such a rare occurrence should be caught.

After working around this I'm a bit puzzled by the NTDDI_VERSION=0x06030000 setting in this build file. It appears that flutter wishes to run on Windows 7 and possibly earlier if possible (I see the try to build for XP settings in this file). If so it seems setting NTDDI_VERSION to 8.1, which is neither the oldest nor newest target, is just a pain point?

**Comment by Hixie** [comment]
@bungeman We're happy to take the patch if you think we need it, but it's not clear from your comments above if you think we need it? Please let us know what you would like to do. Thanks!

**Comment by Hixie** [comment]
@bungeman informs me he won't be able to work on this in the near future so I'm going to close this PR for now. This is definitely an area we should look at in due course though.

**Pull request closed without merging**
