### PR TITLE
Bump minimum android_api_level to 19

### PR DESCRIPTION
**Pull request by mraleph**
We don't support API levels 18 and below anyway. 

I would like to make a change to Dart SDK that requires API level 18 or above.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by reidbaker** [comment]
Please hold on this PR. We have a single google customer that we are waiting on to update their minSdk. ETA is mid next week. I am surprised that FROB didnt fail on this pr. 

cl/551217709

**Comment by mraleph** [comment]
@reidbaker FROB does not fail because these two things are unconnected. AndroidManifest can say minSdk=16 while engine is assuming something newer. For example ARM64 and X64 builds of engine are building with SDK version set to 22 already. See default value for `android_api_level`.

**Comment by reidbaker** [comment]
> @reidbaker FROB does not fail because these two things are unconnected. AndroidManifest can say minSdk=16 while engine C++ is compiled assuming something newer. For example ARM64 and X64 builds of engine are building with SDK version set to 22 already. See default value for `android_api_level`.

Thanks for this explanation

**Review by reidbaker — APPROVED** [review]

**Comment by mraleph** [comment]
@reidbaker thanks for approving! is buildroot autorolled into engine or should I roll manually?

**Comment by reidbaker** [comment]
I actually dont know @chinmaygarde can you answer?

**Comment by mraleph** [comment]
I checked autoroller configurations and I could not find one for buildroot - so I am going to roll manually.

**Comment by chinmaygarde** [comment]
No. There is no buildroot autoroller.

**Pull request merged**
