### PR TITLE
Allow LTO enabled builds on Darwin platforms.

### PR DESCRIPTION
**Pull request by chinmaygarde**
For developer sanity, I am going to add a --disable-lto flag on `//flutter/tools/gn`. Saves 1.6 mb on the release `Flutter.framework` binary (uncompressed).

### CODE REVIEW

**Comment by abarth** [comment]
Why can't this go through cflags or one of the existing variables?

**Comment by chinmaygarde** [comment]
The LTO flags need to be passed to the linkers are well. Also, I thought the `cflags` were per source file while I think of `LTO` as being enabled per build variant. That is, it did not make sense for certain libraries in a build have LTO enabled while others didn't. But maybe that is not the case.

**Comment by abarth** [comment]
Ok.  Does it need to be first, or can it be after toolchain_flags?

**Comment by abarth** [comment]
Will this enable LTO for unoptimized builds?  I think we normally have the default (no arguments) case set for unoptimized and have `//flutter/tools/gn` turn on various optimizations.

**Comment by chinmaygarde** [comment]
> Ok. Does it need to be first, or can it be after toolchain_flags?

It can be after. I moved it.

> Will this enable LTO for unoptimized builds?

Yes. For now, this will be enabled for all builds. In `//flutter/tools/gn`, I will make this conditional. Unfortunately, that is the engine repo.

**Comment by chinmaygarde** [comment]
>  I think we normally have the default (no arguments) case set for unoptimized 

We actually optimize in case of the default invocation with no arguments. We build the debug (as in the Dart product mode) optimized variant.

**Comment by abarth** [comment]
Interesting.  Thanks!  LGTM

**Pull request merged**
