### PR TITLE
Revert "Remove //tools."

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/buildroot#784

Reverting to unblock the Dart -> Engine autoroller. (A partial revert that restores tools/dart/create_updated_flutter_deps.py would also work.)

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
> A partial revert that restores tools/dart/create_updated_flutter_deps.py would also work.

Can the autoroller be patched instead to move the script into its sources? Or does the script need to be in the engine. Its rough not being able to test a free floating script.

**Comment by zanderso** [comment]
> Can the autoroller be patched instead to move the script into its sources? Or does the script need to be in the engine. Its rough not being able to test a free floating script.

Not easily. I believe it would need to be ported to go and live in g3.

**Comment by chinmaygarde** [comment]
I am going to create a partial revert instead.

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
Partial revert.

**Pull request closed without merging**
